---
- name: Configurar
  hosts: db01

  user: vagrant
  become: yes
  vars:
  - dbname: "db01"
  - dbusername: "root"
  - dbuspassword: "dqm50vnc"
  tasks:
    - name: Configurar hosts lab ansible
      lineinfile: 
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
        - 192.168.0.2 control-node
        - 192.168.0.3 app01
        - 192.168.0.4 db01
  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql